leagues:
  FIFA World Cup: 世界杯
  FIFA World Cup (World): 世界杯
  World Cup (World): 世界杯
  Premier League: 英超
  Premier League (England): 英超
  La Liga: 西甲
  La Liga (Spain): 西甲
  Bundesliga: 德甲
  Bundesliga (Germany): 德甲
  Serie A: 意甲
  Serie A (Italy): 意甲
  Ligue 1: 法甲
  Ligue 1 (France): 法甲
  UEFA Champions League: 欧冠
  UEFA Champions League (World): 欧冠
  UEFA Europa League: 欧联
  UEFA Europa League (World): 欧联
  UEFA Europa Conference League: 欧协联
  UEFA Europa Conference League (World): 欧协联
  Championship: 英冠
  Championship (England): 英冠
  2. Bundesliga: 德乙
  2. Bundesliga (Germany): 德乙
  Segunda División: 西乙
  Segunda División (Spain): 西乙
  Serie B: 意乙
  Serie B (Italy): 意乙
  Ligue 2: 法乙
  Ligue 2 (France): 法乙
  Primeira Liga: 葡超
  Primeira Liga (Portugal): 葡超
  Eredivisie: 荷甲
  Eredivisie (Netherlands): 荷甲
  Eerste Divisie: 荷乙
  Eerste Divisie (Netherlands): 荷乙
  Jupiler Pro League: 比甲
  Jupiler Pro League (Belgium): 比甲
  Süper Lig: 土超
  Süper Lig (Turkey): 土超
  Premiership: 苏超
  Premiership (Scotland): 苏超
  Super League 1: 希腊超
  Super League 1 (Greece): 希腊超
  Bundesliga (Austria): 奥甲
  Super League: 瑞士超
  Super League (Switzerland): 瑞士超
  Liga I: 罗甲
  Liga I (Romania): 罗甲
  Premier League (Russia): 俄超
  Ekstraklasa: 波兰超
  Ekstraklasa (Poland): 波兰超
  Superliga: 丹麦超
  Superliga (Denmark): 丹麦超
  Liga Profesional Argentina: 阿甲
  Liga Profesional Argentina (Argentina): 阿甲
  Serie A (Brazil): 巴西甲
  Primera División: 智利甲
  Primera División (Chile): 智利甲
  Veikkausliiga: 芬超
  Veikkausliiga (Finland): 芬超
  Allsvenskan: 瑞典超
  Allsvenskan (Sweden): 瑞典超
  Superettan: 瑞典超甲
  Superettan (Sweden): 瑞典超甲
  League One: 英甲
  League One (England): 英甲
  Eliteserien: 挪超
  Eliteserien (Norway): 挪超
  Premier Division (Ireland): 爱超
  First Division (Ireland): 爱甲
  Úrvalsdeild (Iceland): 冰岛超
  Ykkösliiga: 芬甲
  Ykkösliiga (Finland): 芬甲
  1. Division (Norway): 挪甲
  1. Division (Denmark): 丹麦甲
  Liga 1 (Indonesia): 印尼超
  Liga MX: 墨西超
  Liga MX (Mexico): 墨西超
  3. Liga: 德丙
  3. Liga (Germany): 德丙
  J1 League: 日职联
  J1 League (Japan): 日职联
  J2 League: 日职乙
  J2 League (Japan): 日职乙
  K League 1: 韩K联
  K League 1 (South-Korea): 韩K联
  K League 2: 韩K2联
  K League 2 (South-Korea): 韩K2联
  A-League: 澳超
  A-League (Australia): 澳超
  Pro League: 沙特联
  Pro League (Saudi-Arabia): 沙特联
  Super League (China): 中超
  Major League Soccer: 美职联
  Major League Soccer (USA): 美职联
teams:
  1. FC Heidenheim: 海登海姆
  1. FC Kaiserslautern: 凯泽斯劳滕
  1. FC Köln: 科隆
  1. FC Magdeburg: 马格德堡
  1. FC Nürnberg: 纽伦堡
  1899 Hoffenheim: 霍芬海姆
  A. Italiano: 奥达科斯
  AC Horsens: 霍森斯
  AC Milan: AC米兰
  AC Oulu: 奥卢
  AD Ceuta FC: 休达
  ADO Den Haag: 海牙
  AEK Athens FC: 雅典AEK
  AFC Hermannstadt: 赫曼施塔特
  AFC Wimbledon: AFC温布尔登
  AIK Stockholm: 索尔纳
  AS Roma: 罗马
  AVS: 阿维什镇
  AZ Alkmaar: 阿尔克马尔
  Aalborg: 奥尔堡
  Aalesund: 奥勒松
  Aarhus: 奥胡斯
  Aarhus Fremad: 奥胡斯费马
  Aberdeen: 阿伯丁
  Adelaide United: 阿德莱德联
  Afturelding: 阿费查尔丁
  Ajax: 阿贾克斯
  Akhmat: 格罗兹尼
  Akron: 阿克伦陶里亚蒂
  Al Khaleej Saihat: 塞哈特海湾
  Al Kholood: 拉斯永恒
  Al Najma: 纳杰马体育
  Al Okhdood: 阿科多
  Al Riyadh: 利雅得体育
  Al Shabab: 利雅得青年人
  Al Taawon: 布赖代合作
  Al-Ahli Jeddah: 吉达国民
  Al-Ettifaq: 达曼协作
  Al-Fateh: 哈萨征服
  Al-Fayha: 费哈
  Al-Hazm: 哈森姆
  Al-Hilal Saudi FC: 利雅得新月
  Al-Ittihad FC: 吉达联合
  Al-Nassr: 利雅得胜利
  Al-Qadisiyah FC: 胡拜尔库迪西亚
  Alanyaspor: 阿拉尼亚体育
  Alaves: 阿拉维斯
  Albacete: 阿尔瓦塞特
  Albirex Niigata: 新泻天鹅
  Aldosivi: 阿尔多斯维
  Algeria: 阿尔及利亚
  Almere City FC: 阿尔梅勒城
  Almeria: 阿尔梅里亚
  Alverca: 艾华卡
  Amiens: 亚眠
  Anderlecht: 安德莱赫特
  Angers: 昂热
  Annecy: 昂纳西
  Ansan Greeners: 安山小绿人
  Antalyaspor: 安塔利亚
  Antwerp: 安特卫普
  Arbroath: 阿布罗斯
  Arema FC: 阿雷马
  Argentina: 阿根廷
  Argentinos JRS: 阿根廷青年人
  Arges Pitesti: 阿格斯
  Aris Thessalonikis: 阿里斯
  Arka Gdynia: 阿尔卡
  Arminia Bielefeld: 比勒菲尔德
  Arouca: 阿罗卡
  Arsenal: 阿森纳
  Asan Mugunghwa: 忠南牙山
  Asane: 阿萨纳
  Asteras Tripolis: 特里波利斯
  Aston Villa: 阿斯顿维拉
  Atalanta: 亚特兰大
  Athletic Club: 毕尔巴鄂竞技
  Athlone Town: 阿斯隆城
  Atlanta United FC: 亚特兰大联
  Atlante FC: 亚特兰特
  Atlas: 阿特拉斯
  Atletico Madrid: 马德里竞技
  Atletico Paranaense: 巴拉纳竞技
  Atletico San Luis: 圣路易斯竞技
  Atletico Tucuman: 图库曼竞技
  Atletico-MG: 米内罗竞技
  Atromitos: 阿特罗米托斯
  Auckland: 奥克兰FC
  Austin: 奥斯汀FC
  Australia: 澳大利亚
  Austria: 奥地利
  Austria Vienna: 奥地利维也纳
  Auxerre: 欧塞尔
  Avellino: 阿维利诺
  Avispa Fukuoka: 福冈黄蜂
  B 93: B93哥本哈根
  BK Hacken: 赫根
  BSC Young Boys: 年轻人
  Bahia: 巴伊亚
  Bali United: 巴厘联
  Baltika: 巴蒂卡
  Banfield: 班菲尔德
  Barcelona: 巴塞罗那
  Bari: 巴里
  Barnsley: 巴恩斯利
  Barracas Central: 巴拉卡斯中央
  Bastia: 巴斯蒂亚
  Bayer Leverkusen: 勒沃库森
  Bayern Munich: 拜仁慕尼黑
  Bayern München: 拜仁慕尼黑
  Başakşehir: 巴萨克赛尔
  Beerschot VA: 比肖特VA
  Beijing Guoan: 北京国安
  Belgium: 比利时
  Belgrano Cordoba: 贝尔格拉诺
  Benfica: 本菲卡
  Beşiktaş: 贝西克塔斯
  Bhayangkara FC: 巴杨卡拉泗水联
  Birmingham: 伯明翰
  Blackburn: 布莱克本
  Blackpool: 布莱克浦
  Boca Juniors: 博卡青年
  Bodo/Glimt: 博德闪耀
  Bohemians: 波西米亚人
  Bologna: 博洛尼亚
  Bolton: 博尔顿
  Borussia Dortmund: 多特蒙德
  Borussia Mönchengladbach: 门兴格拉德巴赫
  Bosnia & Herzegovina: 波黑
  Botafogo: 博塔弗戈
  Boulogne: 布洛涅
  Bournemouth: 伯恩茅斯
  Bradford: 布拉德福德
  Brann: 布兰
  Bray Wanderers: 布雷流浪者
  Brazil: 巴西
  Breidablik: 贝雷达比历克
  Brentford: 布伦特福德
  Brighton: 布莱顿
  Brisbane Roar: 布里斯班狮吼
  Bristol City: 布里斯托尔城
  Brondby: 布隆德比
  Bryne: 布莱尼
  Bucheon FC 1995: 富川FC
  Buducnost Podgorica: 布杜诺斯特
  Burgos: 布尔戈斯
  Burnley: 伯恩利
  Burton Albion: 伯顿
  Busan I Park: 釜山偶像
  CF Montreal: 蒙特利尔FC
  CF Pachuca: 帕丘卡
  CFR 1907 Cluj: 克卢日
  CSKA Moscow: 莫斯科中央陆军
  Cadiz: 加的斯
  Cagliari: 卡利亚里
  Cambuur: 坎布尔
  Canada: 加拿大
  Cape Verde Islands: 佛得角
  Cardiff: 卡迪夫城
  Carrarese: 凯勒雷斯
  Casa Pia: 卡萨比亚
  Castellón: 卡斯迪隆
  Catanzaro: 卡坦扎罗
  Ceara: 塞阿拉
  Celje: 采列
  Celta Vigo: 塞尔塔
  Celtic: 凯尔特人
  Central Coast Mariners: 中央海岸水手
  Central Cordoba de Santiago: 科尔多瓦中央
  Cercle Brugge: 色拉格布鲁日
  Cerezo Osaka: 大阪樱花
  Cesena: 切塞纳
  Changchun Yatai: 长春亚泰
  Chapecoense-sc: 沙佩科恩斯
  Charleroi: 沙勒罗瓦
  Charlotte: 夏洛特FC
  Charlton: 查尔顿
  Chelsea: 切尔西
  Chengdu Better City: 成都蓉城
  Cheonan City: 天安城
  Cheongju: 忠北清州
  Chicago Fire: 芝加哥火焰
  Chindia Targoviste: 赤尼达塔高维斯
  Chongqing Tongliang Long: 重庆铜梁龙
  Clermont Foot: 克莱蒙
  Club America: 墨西哥美洲
  Club Brugge KV: 布鲁日
  Club Queretaro: 克雷塔罗
  Club Tijuana: 蒂华纳
  Cobh Ramblers: 科布漫游者
  Cobresal: 科布雷萨尔
  Colo Colo: 科洛科洛
  Colombia: 哥伦比亚
  Colorado Rapids: 科罗拉多急流
  Columbus Crew: 哥伦布机员
  Como: 科莫
  Concepción: 康塞普西翁
  Congo DR: 民主刚果
  Coquimbo Unido: 科其姆波
  Cordoba: 科尔多瓦
  Corinthians: 科林蒂安
  Coritiba: 科里蒂巴
  Cork City: 科克城
  Corvinul Hunedoara: 胡内多阿拉
  Coventry: 考文垂
  Cracovia Krakow: 克拉科维亚
  Cremonese: 克雷莫纳
  Croatia: 克罗地亚
  Cruz Azul: 蓝十字
  Cruzeiro: 克鲁塞罗
  Crystal Palace: 水晶宫
  Csikszereda: FK米耶尔库雷亚丘克
  Cultural Leonesa: 莱昂文体
  Curaçao: 库拉索
  Czech Republic: 捷克
  D. La Serena: 塞雷那
  DC United: 华盛顿联
  Daegu FC: 大邱FC
  Daejeon Citizen: 大田市民
  Dalian Zhixing: 大连英博
  Damac: 达马克
  De Graafschap: 格拉夫夏普
  Defensa Y Justicia: 国防与司法
  Degerfors IF: 代格福什
  Den Bosch: 邓伯什
  Dender: 登德
  Deportes Iquique: 伊基克体育
  Deportes Limache: 利马切颜色
  Deportivo La Coruna: 拉科鲁尼亚
  Deportivo Riestra: 利斯特雷
  Derby: 德比郡
  Derry City: 德里城
  Dewa United: 德瓦
  Dinamo Bucuresti: 布加勒斯特迪纳摩
  Dinamo Makhachkala: 莫斯科迪纳摩
  Dinamo Minsk: 明斯克迪纳摩
  Djurgardens IF: 尤尔加登
  Doncaster: 汤卡斯特
  Dordrecht: 多德勒支
  Drita: 德利塔
  Drogheda United: 德罗赫达联
  Dundalk: 邓多克
  Dundee: 邓迪FC
  Dundee Utd: 邓迪联
  Dunfermline: 邓弗姆林
  Dunkerque: 敦刻尔克
  Dynamo: 马哈奇卡拉迪纳摩
  Dynamo Dresden: 德累斯顿
  Dynamo Kyiv: 基辅迪纳摩
  EIF: EIF埃克纳斯
  Ecuador: 厄瓜多尔
  Egersund: 埃格尔森德
  Egnatia Rrogozhinë: 埃格纳蒂亚
  Egypt: 埃及
  Eibar: 埃瓦尔
  Eintracht Braunschweig: 布伦瑞克
  Eintracht Frankfurt: 法兰克福
  Elche: 埃尔切
  Emmen: 埃门
  Empoli: 恩波利
  England: 英格兰
  Esbjerg: 埃斯比约
  Espanyol: 西班牙人
  Estac Troyes: 特鲁瓦
  Estoril: 埃斯托里尔
  Estrela: 阿马多拉之星
  Estudiantes L.P.: 拉普拉塔大学生
  Estudiantes de Rio Cuarto: 里奥夸尔托学生队
  Everton: 埃弗顿
  Everton de Vina: 埃弗顿VM
  Excelsior: SBV精英
  Exeter City: 埃克塞特城
  Eyüpspor: 埃于普体育
  FC Aarau: 阿劳
  FC Andorra: 安道尔FC
  FC Anyang: 安养FC
  FC Augsburg: 奥格斯堡
  FC BW Linz: BW林茨
  FC Basel 1893: 巴塞尔
  FC Botosani: 波图森尼
  FC Cincinnati: 辛辛那提FC
  FC Copenhagen: 哥本哈根
  FC Dallas: 达拉斯FC
  FC Differdange 03: 邓弗当日
  FC Eindhoven: FC埃因霍温
  FC Fredericia: 弗雷德里西亚
  FC Juarez: 华雷斯
  FC Krasnodar: 克拉斯诺
  FC Levadia Tallinn: 塔林利瓦迪亚
  FC Lugano: 卢加诺
  FC Luzern: 卢塞恩
  FC Midtjylland: 中日德兰
  FC Noah: 诺亚FC
  FC Nordsjaelland: 北西兰
  FC OSS: 奥斯
  FC Orenburg: 奥伦堡
  FC Porto: 波尔图
  FC Rostov: 罗斯托夫
  FC ST. Gallen: 圣加伦
  FC Schalke 04: 沙尔克04
  FC Seoul: 首尔FC
  FC Sion: 锡永
  FC Sochi: 索契
  FC St. Pauli: 圣保利
  FC Thun: 图恩
  FC Tokyo: FC东京
  FC Volendam: 福伦丹
  FC Voluntari: 沃伦塔利
  FC Winterthur: 温特图尔
  FC Zurich: 苏黎世
  FCSB: 布加勒斯特星
  FF Jaro: 雅罗
  FH hafnarfjordur: 哈夫纳夫约杜尔
  FK Crvena Zvezda: 贝尔格莱德红星
  FK Zalgiris Vilnius: 萨尔格里斯
  FSV Mainz 05: 美因茨
  Fagiano Okayama: 冈山绿雉
  Falkenbergs FF: 法尔肯堡
  Falkirk: 福尔柯克
  Famalicao: 法马利康
  Farul Constanta: 法鲁尔
  Fatih Karagümrük: 卡拉古鲁克
  Fenerbahçe: 费内巴切
  Ferencvarosi TC: 费伦茨罗斯
  Feyenoord: 费耶诺德
  Finn Harps: 费恩夏普
  Fiorentina: 佛罗伦萨
  Flamengo: 弗拉门戈
  Fluminense: 弗鲁米嫩塞
  Fortaleza EC: 福塔雷萨
  Fortuna Düsseldorf: 杜塞尔多夫
  Fortuna Sittard: 福图纳锡塔德
  Fram Reykjavik: 弗拉姆
  France: 法国
  Fredrikstad: 腓特烈斯塔
  Frosinone: 弗罗西诺内
  Fulham: 富勒姆
  GIF Sundsvall: 松兹瓦尔
  GIL Vicente: 吉尔维森特
  GKS Katowice: GKS卡托威斯
  GO Ahead Eagles: 前进之鹰
  Gais: 哥德堡盖斯
  Galatasaray: 加拉塔萨雷
  Galway United: 戈尔韦联
  Gamba Osaka: 大阪钢巴
  Gangwon FC: 江原FC
  Gaziantep FK: 加济安泰普
  Genk: 亨克
  Genoa: 热那亚
  Gent: 根特
  Gençlerbirliği S.K.: 根克勒比利吉
  Germany: 德国
  Getafe: 赫塔菲
  Ghana: 加纳
  Gimcheon Sangmu FC: 金泉尚武
  Gimhae City: 金海
  Gimnasia L.P.: 拉普拉塔体操
  Gimnasia M.: 门多萨体操击剑
  Gimpo Citizen: 金浦市民
  Girona: 赫罗纳
  Gnistan: 格尼斯坦
  Godoy Cruz: 戈多伊克鲁斯
  Gornik Zabrze: 扎布热矿工
  Granada CF: 格拉纳达
  Grasshoppers: 草蜢
  Grazer AK: 格拉茨AK
  Gremio: 格雷米奥
  Grenoble: 格勒诺布尔
  Groningen: 格罗宁根
  Guadalajara Chivas: 瓜达拉哈拉
  Guimaraes: 吉马良斯
  Guingamp: 甘冈
  Gwangju FC: 光州FC
  Gyeongnam FC: 庆南FC
  Göztepe: 哥兹塔比
  HB Koge: HB克厄
  HJK Helsinki: 赫尔辛基
  Haiti: 海地
  Haka: 哈卡
  Halmstad: 哈姆斯塔德
  Ham-Kam: 汉坎
  Hamburger SV: 汉堡
  Hammarby FF: 哈马比
  Hammarby Talang: 哈马比TFF
  Hamrun Spartans: 阿姆伦斯巴达
  Hangzhou Greentown: 浙江队
  Hannover 96: 汉诺威96
  Haugesund: 海于格松
  Heart Of Midlothian: 哈茨
  Heerenveen: 海伦芬
  Hellas Verona: 维罗纳
  Helmond Sport: 赫尔蒙德
  Helsingborg: 赫尔辛堡
  Henan Jianye: 河南队
  Heracles: 赫拉克勒斯
  Hertha BSC: 柏林赫塔
  Hibernian: 希伯尼安
  Hillerød: 希勒罗德
  Hobro: 霍布罗
  Holstein Kiel: 荷尔斯泰因
  Houston Dynamo: 休斯顿迪纳摩
  Huachipato: 瓦奇巴托
  Huddersfield: 哈德斯菲尔德
  Huesca: 韦斯卡
  Hull City: 赫尔城
  Huracan: 飓风队
  Hvidovre: 哈维德夫
  Hwaseong: 华城FC
  IA Akranes: IA阿克拉内斯
  IBV Vestmannaeyjar: IBV韦斯特曼纳
  IF Brommapojkarna: 布洛马波卡纳
  IF Elfsborg: 埃尔夫斯堡
  IFK Goteborg: 哥德堡
  IFK Norrkoping: 北雪平
  IFK Varnamo: IFK瓦纳默
  IK brage: 布莱格
  Ilves: 埃尔维斯
  Incheon United: 仁川联
  Independ. Rivadavia: 门多萨独立
  Independiente: 阿根廷独立
  Instituto Cordoba: 科尔多瓦学院
  Inter: 国际米兰
  Inter Miami: 迈阿密国际
  Inter Turku: 图尔库国际
  Internacional: 巴西国际
  Ipswich: 伊普斯维奇
  Iran: 伊朗
  Iraq: 伊拉克
  Ivory Coast: 科特迪瓦
  JEF United Chiba: 千叶市原
  JIPPO: 基柏
  Jagiellonia: 雅盖隆
  Japan: 日本
  Jeju United FC: 济州SKFC
  Jeonbuk Motors: 全北现代
  Jeonnam Dragons: 全南天龙
  Jong AZ: 阿尔克马尔青年队
  Jong Ajax: 阿贾克斯青年队
  Jong PSV U21: 埃因霍温青年队
  Jong Utrecht: 乌德勒支青年队
  Jordan: 约旦
  Juve Stabia: 史泰比亚
  Juventude: 尤文图德
  Juventus: 尤文图斯
  JäPS: 查普斯
  KA Akureyri: KA阿克雷里
  KFUM Oslo: KFUM奥斯陆
  KR Reykjavik: 雷克雅未克
  KV Mechelen: 梅赫伦
  KVC Westerlo: 韦斯特洛
  Kairat Almaty: 凯拉特
  Kalmar FF: 卡尔马
  Karlsruher SC: 卡尔斯鲁厄
  Kashima: 鹿岛鹿角
  Kashiwa Reysol: 柏太阳神
  Kasımpaşa: 卡斯帕萨
  Kawasaki Frontale: 川崎前锋
  Kayserispor: 开塞利体育
  Keflavik: 凯夫拉维克
  Kerry: 凯里FC
  Kifisia: 基菲萨
  Kilmarnock: 基尔马诺克
  Klubi-04: 克鲁比04
  Kocaelispor: 高尔卡利
  Kolding IF: 科灵
  Kongsvinger: 康斯文格
  Konyaspor: 科尼亚
  Kooteepee: KTP科特卡
  Korona Kielce: 凯尔采科罗纳
  Kristiansund BK: 克里斯蒂安松
  Krylia Sovetov: 苏维埃之翼
  KuPS: 古比斯
  Kyoto Sanga: 京都不死鸟
  KäPa: 卡亚尼卡帕
  Lahti: 拉蒂赫
  Landskrona BoIS: 兰斯科罗纳
  Lanus: 拉努斯
  Larisa: 拉里萨
  Las Palmas: 拉斯帕尔马斯
  Lask Linz: 林茨
  Lausanne: 洛桑
  Laval: 拉瓦勒
  Lazio: 拉齐奥
  Le Havre: 勒阿弗尔
  Le Mans: 勒芒
  Lecce: 莱切
  Lech Poznan: 波兹南莱赫
  Lechia Gdansk: 格但斯克
  Leeds: 利兹联
  Leganes: 莱加内斯
  Legia Warszawa: 华沙莱吉亚
  Leicester: 莱斯特城
  Lens: 朗斯
  Leon: 莱昂
  Levadiakos: 莱瓦贾克斯
  Levante: 莱万特
  Leyton Orient: 莱顿东方
  Lille: 里尔
  Lillestrom: 利勒斯特罗姆
  Lincoln: 林肯城
  Lincoln Red Imps FC: 林肯红魔
  Liverpool: 利物浦
  Livingston: 利文斯顿
  Liège: RFC列日
  Ljungskile SK: 卢恩斯基尔
  Lokomotiv: 莫火车头
  Lommel United: 洛默尔
  Longford Town: 郎福德城
  Lorient: 洛里昂
  Los Angeles FC: 洛杉矶FC
  Los Angeles Galaxy: 洛杉矶银河
  Ludogorets: 卢多格雷茨
  Luton: 卢顿
  Lyn: 利恩
  Lyngby: 林比
  Lyon: 里昂
  MP: MP米可力
  MVV: 马斯特里赫特
  Macarthur: 麦克阿瑟FC
  Machida Zelvia: 町田泽维亚
  Malaga: 马拉加
  Mallorca: 马略卡
  Malmo FF: 马尔默
  Malut United: 马路特联
  Manchester City: 曼城
  Manchester United: 曼联
  Mansfield Town: 曼斯菲尔德
  Mantova: 曼托瓦
  Mariehamn: 玛丽港
  Marseille: 马赛
  Mazatlán: 马萨特兰
  Meizhou Kejia: 梅州客家
  Melbourne City: 墨尔本城
  Melbourne Victory: 墨尔本胜利
  Metaloglobus: 梅塔洛格布斯
  Metz: 梅斯
  Mexico: 墨西哥
  Middelfart: 米德法特
  Middlesbrough: 米德尔斯堡
  Millwall: 米尔沃尔
  Minnesota United FC: 明尼苏达联
  Mirandes: 米兰德斯
  Mirassol: 米拉索
  Mito Hollyhock: 水户蜀葵
  Mjallby AIF: 米亚尔比
  Modena: 摩德纳
  Molde: 莫尔德
  Monaco: 摩纳哥
  Monterrey: 蒙特雷
  Montpellier: 蒙彼利埃
  Monza: 蒙扎
  Moreirense: 莫雷拉人
  Morocco: 摩洛哥
  Moss: 摩斯
  Motherwell: 马瑟韦尔
  Motor Lublin: 摩托路宾
  NAC Breda: 布雷达
  NEC Nijmegen: 奈梅亨
  NEOM: 新未来城体育
  Nacional: 马德拉国民
  Nagoya Grampus: 名古屋鲸鱼
  Nancy: 南锡
  Nantes: 南特
  Napoli: 那不勒斯
  Nashville SC: 纳什维尔FC
  Necaxa: 内卡萨
  Netherlands: 荷兰
  New England Revolution: 新英格兰革命
  New York City FC: 纽约城
  New York Red Bulls: 纽约红牛
  New Zealand: 新西兰
  Newcastle: 纽卡斯尔联
  Newcastle Jets: 纽卡斯尔喷气机
  Newells Old Boys: 纽维尔老男孩
  Nice: 尼斯
  Nieciecza: 特马利卡
  Nizhny Novgorod: 下诺夫哥罗德
  Norrby IF: 诺尔比
  Northampton: 备案浦东
  Norway: 挪威
  Norwich: 诺维奇
  Nottingham Forest: 诺丁汉森林
  Nublense: 努布伦斯
  O'Higgins: 奥伊金斯
  ODD Ballklubb: 奥德
  OFI: OFI克里特
  OH Leuven: 旧海弗莱鲁汶
  Oddevold: 奥迪沃特
  Odense: 欧登塞
  Olympiakos Piraeus: 奥林匹亚科斯
  Orebro SK: 奥雷布洛
  Orgryte IS: 奥尔格里特
  Orlando City SC: 奥克兰城
  Osasuna: 奥萨苏纳
  Osters IF: 奥斯达
  Ostersunds FK: 厄斯特松德
  Oviedo: 皇家奥维耶多
  Oxford United: 牛津联
  Oţelul: 加拉茨钢铁
  PAOK: 塞萨洛尼基
  PAU: 波城
  PEC Zwolle: 兹沃勒
  PK-35: PK35万塔
  PSBS Biak Numfor: 巴克伦佛
  PSIM Yogyakarta: 永亚卡达
  PSM Makassar: PSM望加锡
  PSV Eindhoven: 埃因霍温
  Padova: 帕多瓦
  Pafos: 帕福斯FC
  Paju Citizen: 坡州前线
  Palermo: 巴勒莫
  Palestino: 帕莱斯蒂诺
  Palmeiras: 帕尔梅拉斯
  Panama: 巴拿马
  Panathinaikos: 帕纳辛纳科斯
  Panetolikos: 帕纳托利克斯
  Panserraikos: 潘塞莱科斯
  Paraguay: 巴拉圭
  Paris FC: 巴黎FC
  Paris Saint Germain: 巴黎圣日耳曼
  Parma: 帕尔马
  Partick: 帕尔蒂克
  Patro Eisden: 艾斯登
  Persebaya Surabaya: 帕尔斯巴亚
  Persepam Madura Utd: 马都拉联
  Persib Bandung: 万隆
  Persija: 佩西加雅加达
  Persijap: 杰帕拉
  Persik Kediri: 佩斯克谏义里
  Persis Solo: 伯希索罗
  Persita: 培斯塔坦格朗
  Perth Glory: 珀斯光荣
  Pescara: 佩斯卡拉
  Peterborough: 彼得堡联
  Petrolul Ploiesti: 佩特罗鲁
  Philadelphia Union: 费城联合
  Piast Gliwice: 皮亚斯特
  Pisa: 比萨
  Platense: 普拉滕斯
  Plymouth: 普利茅斯
  Plzen: 比尔森胜利
  Pogon Szczecin: 什切青波贡
  Pohang Steelers: 浦项铁人
  Port Vale: 维尔港
  Portland Timbers: 波特兰伐木工
  Portsmouth: 朴茨茅斯
  Portugal: 葡萄牙
  Preston: 普雷斯顿
  Preußen Münster: 普鲁士明斯特
  Puebla: 普埃布拉
  Pusamania Borneo: 婆罗洲FC
  QPR: 女王公园
  Qarabag: 卡拉巴克
  Qatar: 卡塔尔
  Qingdao Jonoon: 青岛海牛
  Qingdao Youth Island: 青岛西海岸
  RAAL La Louvière: 拉路维尔
  RB Bragantino: 布拉干蒂诺RB
  RB Leipzig: RB莱比锡
  RED Star FC 93: 红星
  Racing Club: 竞技
  Racing Santander: 桑坦德竞技
  Radomiak Radom: 拉多米亚克
  Raków Częstochowa: 琴斯托霍瓦
  Randers FC: 兰讷斯
  Rangers: 流浪者
  Ranheim: 兰黑姆
  Rapid: 布加勒斯特快速
  Rapid Vienna: 维也纳快速
  Raufoss: 诺霍斯
  Rayo Vallecano: 巴列卡诺
  Reading: 雷丁
  Real Betis: 皇家贝蒂斯
  Real Madrid: 皇家马德里
  Real Salt Lake: 皇家盐湖城
  Real Sociedad: 皇家社会
  Real Sociedad II: 皇家社会B队
  Red Bull Salzburg: 萨尔茨堡红牛
  Reggiana: 雷吉亚纳
  Reims: 兰斯
  Remo: 雷莫
  Rennes: 雷恩
  Ried: 里德
  Rio Ave: 里奥阿维
  River Plate: 河床
  Rizespor: 里泽体育
  Roda: 罗达JC
  Rodez: 罗德兹
  Rosario Central: 罗萨里奥中央
  Rosenborg: 罗森博格
  Rot-Weiß Essen: 埃森
  Rotherham: 罗瑟汉姆
  Rotor Volgograd: 伏尔加格勒
  Rouen: 鲁昂
  Rubin: 喀山
  Rīgas FS: 里加足球学院
  SC Braga: 布拉加
  SC Freiburg: 弗赖堡
  SC Paderborn 07: 帕德博恩
  SCR Altach: 阿尔塔奇
  SHANGHAI SIPG: 上海海港
  SJK: 塞纳乔其
  SJK Akatemia: SJK学院
  ST Mirren: 圣米伦
  SV Darmstadt 98: 达姆斯塔特
  SV Elversberg: 艾禾斯堡
  Saint Etienne: 圣埃蒂安
  Sampdoria: 桑普多利亚
  Samsunspor: 萨姆松体育
  San Diego: 圣地亚哥FC
  San Jose Earthquakes: 圣何塞地震
  San Lorenzo: 圣索洛伦
  San Martin S.J.: 圣胡安圣马丁
  Sandefjord: 桑德菲杰
  Sandnes ULF: 桑德尼斯
  Sandviken: 桑德维根斯
  Sanfrecce Hiroshima: 广岛三箭
  Santa Clara: 圣克拉拉
  Santos: 桑托斯
  Santos Laguna: 桑托斯拉古纳
  Sao Paulo: 圣保罗
  Sarmiento Junin: 萨米恩托
  Sarpsborg 08 FF: 萨普斯堡
  Sassuolo: 萨索洛
  Saudi Arabia: 沙特阿拉伯
  Scotland: 苏格兰
  Seattle Sounders: 西雅图海湾人
  Semen Padang: 塞曼巴东
  Senegal: 塞内加尔
  Seongnam FC: 城南FC
  Seoul E-Land FC: 首尔衣恋
  Sepsi OSK Sfantu Gheorghe: 舍佩斯
  Servette FC: 塞尔维特
  Sevilla: 塞维利亚
  Shamrock Rovers: 沙姆洛克
  Shandong Luneng: 山东泰山
  Shanghai Shenhua: 上海申花
  Sheffield Utd: 谢菲联
  Sheffield Wednesday: 谢周三
  Shelbourne: 舒尔本
  Shenyang Urban: 辽宁铁人
  Shimizu S-pulse: 清水心跳
  Shkendija: 斯肯迪亚
  Shonan Bellmare: 湘南丽海
  Sichuan Jiuniu: 深圳新鹏城
  Silkeborg: 锡尔克堡
  Sirius: 天狼星
  Slavia Praha: 布拉格斯拉维亚
  Sligo Rovers: 斯莱戈流浪者
  Slovan Bratislava: 布拉迪斯拉发
  Sogndal: 松达尔
  Sonderjyske: 桑德捷斯基
  South Africa: 南非
  South Korea: 韩国
  Southampton: 南安普顿
  SpVgg Greuther Fürth: 菲尔特
  Spain: 西班牙
  Sparta Rotterdam: 鹿特丹斯巴达
  Spartak Moscow: 莫斯巴达
  Spezia: 斯佩齐亚
  Sport Recife: 累西腓体育
  Sporting CP: 葡萄牙体育
  Sporting Gijon: 希洪竞技
  Sporting Kansas City: 堪萨斯城竞技
  St Patrick's Athl.: 圣帕特里克竞技
  St. Louis City: 圣路易斯城
  St. Truiden: 圣图尔登
  Stabaek: 斯塔贝克
  Stade Brestois 29: 布雷斯特
  Standard Liege: 标准列日
  Start: 斯达
  Stevenage: 斯蒂夫维奇
  Stjarnan: 斯塔尔南
  Stockport County: 斯托克港
  Stoke City: 斯托克城
  Strasbourg: 斯特拉斯堡
  Strommen: 斯托曼
  Stromsgodset: 斯托姆加斯特
  Sturm Graz: 格拉茨风暴
  Sudtirol: 南蒂罗尔
  Sunderland: 桑德兰
  Suwon Bluewings: 水原三星
  Suwon City FC: 水原FC
  Swansea: 斯旺西
  Sweden: 瑞典
  Switzerland: 瑞士
  Sydney: 悉尼FC
  TSV Hartberg: 哈特堡格
  Talleres Cordoba: 塔勒雷斯
  Telstar: 特尔斯达
  Thor Akureyri: 托尔阿克雷里
  Tianjin Teda: 天津津门虎
  Tigre: 提格雷
  Tigres UANL: 老虎大学
  Tokyo Verdy: 东京绿茵
  Toluca: 托卢卡
  Tondela: 通德拉
  Torino: 都灵
  Toronto FC: 多伦多FC
  Torreense: 托伦斯
  Tottenham: 热刺
  Toulouse: 图卢兹
  Trabzonspor: 特拉布宗
  Treaty United: 条约联
  Trelleborg: 特雷勒堡
  Tromso: 特罗姆瑟
  Tunisia: 突尼斯
  Turku PS: TPS图尔库
  Twente: 特温特
  Türkiye: 土耳其
  U. Catolica: 天主大学
  U.N.A.M. - Pumas: 美洲狮
  UCD: 都柏林大学
  USA: 美国
  Udinese: 乌迪内斯
  Ulsan Hyundai FC: 蔚山HD
  Umeå FC: 于默奥
  Union Berlin: 柏林联合
  Union Espanola: 西班牙联合
  Union La Calera: 拉卡莱拉联
  Union Santa Fe: 圣塔菲联
  Union St. Gilloise: 圣吉罗斯
  Unirea Slobozia: 斯洛博齐亚
  United Nordic: 北欧联FC
  Universidad de Chile: 智利大学
  Universidad de Concepcion: 康塞普西翁大学
  Universitatea Cluj: 克卢日大学
  Universitatea Craiova: 克拉约瓦大学
  Ural: 乌拉尔
  Urawa: 浦和红钻
  Uruguay: 乌拉圭
  Uta Arad: UTA阿拉德
  Utrecht: 乌德勒支
  Utsikten: 尤特斯科腾
  Uzbekistan: 乌兹别克斯坦
  V-varen Nagasaki: 长崎成功丸
  VPS: VPS瓦萨
  VVV Venlo: 芬洛
  Valencia: 瓦伦西亚
  Valerenga: 瓦勒伦加
  Valladolid: 巴拉多利德
  Valur Reykjavik: 瓦鲁尔
  Vancouver Whitecaps: 温哥华白浪
  Varbergs BoIS FC: 瓦尔贝里
  Vasco DA Gama: 瓦斯科达伽马
  Vasteras SK FK: 瓦斯特拉斯
  Vejle: 瓦埃勒
  Velez Sarsfield: 萨斯菲尔德
  Venezia: 威尼斯
  Vestri: 维斯特里
  VfB Stuttgart: 斯图加特
  VfL Bochum: 波鸿
  VfL Wolfsburg: 沃尔夫斯堡
  Viborg: 维堡
  Viking: 维京
  Vikingur Reykjavik: 维京古
  Villarreal: 比利亚雷亚尔
  Virtus Entella: 恩特拉
  Vissel Kobe: 神户胜利船
  Vitesse: 维特斯
  Vitoria: 维多利亚
  Volos NFC: 沃格斯NPS
  WSG Wattens: WSG蒂罗尔
  Waalwijk: 瓦尔韦克
  Waterford: 沃特福德联
  Watford: 沃特福德
  Wellington Phoenix: 惠灵顿凤凰
  Werder Bremen: 云达不莱梅
  West Brom: 西布罗姆维奇
  West Ham: 西汉姆联
  Western Sydney Wanderers: 西悉尼流浪者
  Wexford: 韦克斯福德
  Widzew Łódź: 维德祖罗兹
  Wigan: 维冈竞技
  Willem II: 威廉二世
  Wisla Plock: 华沙普洛克
  Wolfsberger AC: 沃尔夫斯贝格
  Wolves: 狼队
  Wrexham: 雷克瑟姆
  Wuhan Three Towns: 武汉三镇
  Wycombe: 韦康比流浪者
  Yokohama F. Marinos: 横滨水手
  Yokohama FC: 横滨FC
  Yongin City: 龙仁FC
  Yunnan Yukun: 云南玉昆
  Zaglebie Lubin: 卢宾
  Zaragoza: 萨拉戈萨
  Zenit: 泽尼特
  Zrinjski: 日林斯基
  Zulte Waregem: 瓦勒海姆
  hodd: 贺特
