leagues:
  Premier League: 英超
  Premier League (England): 英超
  La Liga: 西甲
  La Liga (Spain): 西甲
  Bundesliga: 德甲
  Bundesliga (Germany): 德甲
  Serie A: 意甲
  Serie A (Italy): 意甲
  Ligue 1: 法甲
  Ligue 1 (France): 法甲
  UEFA Champions League: 欧冠
  UEFA Champions League (World): 欧冠
  UEFA Europa League: 欧联
  UEFA Europa League (World): 欧联
  UEFA Europa Conference League: 欧协联
  UEFA Europa Conference League (World): 欧协联
  Championship: 英冠
  Championship (England): 英冠
  2. Bundesliga: 德乙
  2. Bundesliga (Germany): 德乙
  Segunda División: 西乙
  Segunda División (Spain): 西乙
  Serie B: 意乙
  Serie B (Italy): 意乙
  Ligue 2: 法乙
  Ligue 2 (France): 法乙
  Primeira Liga: 葡超
  Primeira Liga (Portugal): 葡超
  Eredivisie: 荷甲
  Eredivisie (Netherlands): 荷甲
  Eerste Divisie: 荷乙
  Eerste Divisie (Netherlands): 荷乙
  Jupiler Pro League: 比甲
  Jupiler Pro League (Belgium): 比甲
  Süper Lig: 土超
  Süper Lig (Turkey): 土超
  Premiership: 苏超
  Premiership (Scotland): 苏超
  Super League 1: 希腊超
  Super League 1 (Greece): 希腊超
  Bundesliga (Austria): 奥甲
  Super League: 瑞士超
  Super League (Switzerland): 瑞士超
  Liga I: 罗甲
  Liga I (Romania): 罗甲
  Premier League (Russia): 俄超
  Ekstraklasa: 波兰超
  Ekstraklasa (Poland): 波兰超
  Superliga: 丹麦超
  Superliga (Denmark): 丹麦超
  Liga Profesional Argentina: 阿甲
  Liga Profesional Argentina (Argentina): 阿甲
  Serie A (Brazil): 巴西甲
  Primera División: 智利甲
  Primera División (Chile): 智利甲
  Veikkausliiga: 芬超
  Veikkausliiga (Finland): 芬超
  Allsvenskan: 瑞典超
  Allsvenskan (Sweden): 瑞典超
  Superettan: 瑞典超甲
  Superettan (Sweden): 瑞典超甲
  League One: 英甲
  League One (England): 英甲
  Eliteserien: 挪超
  Eliteserien (Norway): 挪超
  3. Liga: 德丙
  3. Liga (Germany): 德丙
  J1 League: 日职联
  J1 League (Japan): 日职联
  J2 League: 日职乙
  J2 League (Japan): 日职乙
  K League 1: 韩K联
  K League 1 (South-Korea): 韩K联
  K League 2: 韩K2联
  K League 2 (South-Korea): 韩K2联
  A-League: 澳超
  A-League (Australia): 澳超
  Pro League: 沙特联
  Pro League (Saudi-Arabia): 沙特联
  Super League (China): 中超
  Major League Soccer: 美职联
  Major League Soccer (USA): 美职联
teams:
  1. FC Kaiserslautern: 凯泽斯劳滕
  1. FC Magdeburg: 马格德堡
  1. FC Nürnberg: 纽伦堡
  AFC Hermannstadt: 赫曼施塔特
  AIK Stockholm: AIK索尔纳
  AS Roma: 罗马
  AZ Alkmaar: 阿尔克马尔
  Ajax: 阿贾克斯
  Alverca: 阿尔韦卡
  Arsenal: 阿森纳
  Atalanta: 亚特兰大
  Atletico Madrid: 马德里竞技
  Bayer Leverkusen: 勒沃库森
  Bayern Munich: 拜仁慕尼黑
  Benfica: 本菲卡
  BK Hacken: 赫根
  Bologna: 博洛尼亚
  Bodo/Glimt: 博德闪耀
  Bournemouth: 伯恩茅斯
  Brann: 布兰
  Brentford: 布伦特福德
  Brighton: 布莱顿
  Burnley: 伯恩利
  Cagliari: 卡利亚里
  Cardiff: 卡迪夫城
  Casa Pia: 卡萨皮亚
  Catanzaro: 卡坦扎罗
  Chelsea: 切尔西
  Como: 科莫
  Crystal Palace: 水晶宫
  Deportivo La Coruna: 拉科鲁尼亚
  Dinamo Bucuresti: 布加勒斯特迪纳摩
  Dynamo Dresden: 德累斯顿迪纳摩
  Everton: 埃弗顿
  Feyenoord: 费耶诺德
  Fiorentina: 佛罗伦萨
  Fortuna Düsseldorf: 杜塞尔多夫
  Frosinone: 弗罗西诺内
  Gais: 哥德堡盖斯
  Genoa: 热那亚
  GIL Vicente: 吉维森特
  GO Ahead Eagles: 前进之鹰
  Groningen: 格罗宁根
  Guimaraes: 吉马良斯
  Hammarby FF: 哈马比
  Hannover 96: 汉诺威96
  Heerenveen: 海伦芬
  Hellas Verona: 维罗纳
  Heracles: 赫拉克勒斯
  Hertha BSC: 柏林赫塔
  Holstein Kiel: 荷尔斯泰因基尔
  Inter Turku: 图尔库国际
  Inter: 国际米兰
  Juventus: 尤文图斯
  Kalmar FF: 卡尔马
  Karlsruher SC: 卡尔斯鲁厄
  Lazio: 拉齐奥
  Lecce: 莱切
  Leeds: 利兹联
  Leganes: 莱加内斯
  Liverpool: 利物浦
  Manchester City: 曼城
  Manchester United: 曼联
  Monza: 蒙扎
  NAC Breda: 布雷达
  Napoli: 那不勒斯
  NEC Nijmegen: 奈梅亨
  Newcastle: 纽卡斯尔联
  Nottingham Forest: 诺丁汉森林
  Palermo: 巴勒莫
  Parma: 帕尔马
  PEC Zwolle: 兹沃勒
  Pisa: 比萨
  PSV Eindhoven: PSV埃因霍温
  Rio Ave: 里奥阿维
  SC Braga: 布拉加
  SC Paderborn 07: 帕德博恩
  Sassuolo: 萨索洛
  Sevilla: 塞维利亚
  Sparta Rotterdam: 鹿特丹斯巴达
  Sporting CP: 葡萄牙体育
  Sporting Gijon: 希洪竞技
  Sunderland: 桑德兰
  Swansea: 斯旺西
  Torino: 都灵
  Tottenham: 托特纳姆热刺
  Twente: 特温特
  Udinese: 乌迪内斯
  Utrecht: 乌德勒支
  Valencia: 瓦伦西亚
  VfL Bochum: 波鸿
  VfL Wolfsburg: 沃尔夫斯堡
  Villarreal: 比利亚雷亚尔
  West Ham: 西汉姆联
  Wolves: 狼队
  Real Madrid: 皇家马德里
  Athletic Club: 毕尔巴鄂竞技
  Barcelona: 巴塞罗那
  Alaves: 阿拉维斯
  Rayo Vallecano: 巴列卡诺
  Real Betis: 皇家贝蒂斯
  Levante: 莱万特
  Celta Vigo: 塞尔塔
  Espanyol: 西班牙人
  Real Sociedad: 皇家社会
  Getafe: 赫塔费
  Osasuna: 奥萨苏纳
  Girona: 赫罗纳
  Elche: 埃尔切
  Mallorca: 马略卡
  Oviedo: 奥维耶多
