aliases:
  - entity_type: team
    source_name: oddspapi
    canonical_name: Wolves
    alias_name: Wolverhampton Wanderers
  - entity_type: team
    source_name: oddspapi
    canonical_name: QPR
    alias_name: Queens Park Rangers
  - entity_type: team
    source_name: oddspapi
    canonical_name: Krylia Sovetov
    alias_name: PFK Krylia Sovetov Samara
  - entity_type: team
    source_name: oddspapi
    canonical_name: Dynamo
    alias_name: FK Dinamo Moscow
  - entity_type: team
    source_name: oddspapi
    canonical_name: AIK Stockholm
    alias_name: AIK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Vasteras SK FK
    alias_name: Vasteraas SK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Hammarby FF
    alias_name: Hammarby IF
  - entity_type: team
    source_name: oddspapi
    canonical_name: Rosenborg
    alias_name: Rosenborg BK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Lillestrom
    alias_name: Lillestroem SK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Valerenga
    alias_name: Vaalerenga IF
  - entity_type: team
    source_name: oddspapi
    canonical_name: hodd
    alias_name: Hoedd IL
  - entity_type: team
    source_name: oddspapi
    canonical_name: Strommen
    alias_name: Stroemmen IF
  - entity_type: team
    source_name: oddspapi
    canonical_name: Ham-Kam
    alias_name: HamKam
  - entity_type: team
    source_name: oddspapi
    canonical_name: Sarpsborg 08 FF
    alias_name: Sarpsborg 08
  - entity_type: team
    source_name: oddspapi
    canonical_name: Aalesund
    alias_name: Aalesunds FK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Brann
    alias_name: SK Brann
  - entity_type: team
    source_name: oddspapi
    canonical_name: Fredrikstad
    alias_name: Fredrikstad FK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Molde
    alias_name: Molde FK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Sandefjord
    alias_name: Sandefjord Fotball
  - entity_type: team
    source_name: oddspapi
    canonical_name: Start
    alias_name: IK Start
  - entity_type: team
    source_name: oddspapi
    canonical_name: Tromso
    alias_name: Tromsoe IL
  - entity_type: team
    source_name: oddspapi
    canonical_name: Viking
    alias_name: Viking FK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Ilves
    alias_name: Tampereen Ilves
  - entity_type: team
    source_name: oddspapi
    canonical_name: KuPS
    alias_name: Kuopion Palloseura
  - entity_type: team
    source_name: oddspapi
    canonical_name: SJK
    alias_name: Seinajoen JK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Inter Turku
    alias_name: FC Inter Turku
  - entity_type: team
    source_name: oddspapi
    canonical_name: VPS
    alias_name: Vaasan Palloseura
  - entity_type: team
    source_name: oddspapi
    canonical_name: Turku PS
    alias_name: Turun Palloseura
  - entity_type: team
    source_name: oddspapi
    canonical_name: Lahti
    alias_name: FC Lahti
  - entity_type: team
    source_name: oddspapi
    canonical_name: Mariehamn
    alias_name: IFK Mariehamn
  - entity_type: team
    source_name: oddspapi
    canonical_name: Gnistan
    alias_name: IF Gnistan
  - entity_type: team
    source_name: oddspapi
    canonical_name: EIF
    alias_name: Ekenas Idrottsforening
  - entity_type: team
    source_name: oddspapi
    canonical_name: Gençlerbirliği S.K.
    alias_name: Genclerbirligi SK
  - entity_type: team
    source_name: oddspapi
    canonical_name: Kasımpaşa
    alias_name: Kasimpasa Istanbul
  - entity_type: team
    source_name: oddspapi
    canonical_name: Sonderjyske
    alias_name: Soenderjyske
  - entity_type: team
    source_name: oddspapi
    canonical_name: Brondby
    alias_name: Broendby IF
  - entity_type: team
    source_name: oddspapi
    canonical_name: Aarhus
    alias_name: AGF Aarhus
  - entity_type: team
    source_name: oddspapi
    canonical_name: Rennes
    alias_name: Stade Rennais FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Marseille
    alias_name: Olympique Marseille
  - entity_type: team
    source_name: oddspapi
    canonical_name: Stade Brestois 29
    alias_name: Stade Brest 29
  - entity_type: team
    source_name: oddspapi
    canonical_name: Grasshoppers
    alias_name: Grasshopper Club Zurich
  - entity_type: team
    source_name: oddspapi
    canonical_name: BSC Young Boys
    alias_name: Young Boys Bern
  - entity_type: team
    source_name: oddspapi
    canonical_name: Lausanne
    alias_name: Lausanne-Sport
  - entity_type: team
    source_name: oddspapi
    canonical_name: River Plate
    alias_name: CA River Plate (ARG)
  - entity_type: team
    source_name: oddspapi
    canonical_name: Belgrano Cordoba
    alias_name: CA Belgrano de Cordoba
  - entity_type: team
    source_name: oddspapi
    canonical_name: Argentinos JRS
    alias_name: Argentinos Juniors
  - entity_type: team
    source_name: oddspapi
    canonical_name: Gimnasia L.P.
    alias_name: Gimnasia y Esgrima La Plata
  - entity_type: team
    source_name: oddspapi
    canonical_name: Union Santa Fe
    alias_name: Union de Santa Fe
  - entity_type: team
    source_name: oddspapi
    canonical_name: Estudiantes L.P.
    alias_name: Estudiantes de La Plata
  - entity_type: team
    source_name: oddspapi
    canonical_name: Racing Club
    alias_name: Racing Club Avellaneda
  - entity_type: team
    source_name: oddspapi
    canonical_name: Independ. Rivadavia
    alias_name: Independiente Rivadavia
  - entity_type: team
    source_name: oddspapi
    canonical_name: Talleres Cordoba
    alias_name: CA Talleres de Cordoba
  - entity_type: team
    source_name: oddspapi
    canonical_name: Estudiantes de Rio Cuarto
    alias_name: Estudiantes Rio Cuarto
  - entity_type: team
    source_name: oddspapi
    canonical_name: Instituto Cordoba
    alias_name: Instituto AC Cordoba
  - entity_type: team
    source_name: oddspapi
    canonical_name: Newells Old Boys
    alias_name: Newell's Old Boys
  - entity_type: team
    source_name: oddspapi
    canonical_name: Gimnasia M.
    alias_name: Gimnasia y Esgrima Mendoza
  - entity_type: team
    source_name: oddspapi
    canonical_name: U. Catolica
    alias_name: Universidad Catolica
  - entity_type: team
    source_name: oddspapi
    canonical_name: D. La Serena
    alias_name: Deportes La Serena
  - entity_type: team
    source_name: oddspapi
    canonical_name: A. Italiano
    alias_name: Audax Italiano
  - entity_type: team
    source_name: oddspapi
    canonical_name: Everton de Vina
    alias_name: CD Everton Vina del Mar
  - entity_type: team
    source_name: oddspapi
    canonical_name: Shanghai Shenhua
    alias_name: Shanghai Shenhua FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: SHANGHAI SIPG
    alias_name: Shanghai Port FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Tianjin Teda
    alias_name: Tianjin Jinmen Tiger
  - entity_type: team
    source_name: oddspapi
    canonical_name: Hangzhou Greentown
    alias_name: Zhejiang FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Shandong Luneng
    alias_name: Shandong Taishan FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Chengdu Better City
    alias_name: Chengdu Rongcheng
  - entity_type: team
    source_name: oddspapi
    canonical_name: Qingdao Jonoon
    alias_name: Qingdao Hainiu FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Shenyang Urban
    alias_name: Liaoning Tieren FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Chongqing Tongliang Long
    alias_name: Chongqing Tonglianglong FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Wuhan Three Towns
    alias_name: Wuhan Three Towns FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Dalian Zhixing
    alias_name: Dalian Yingbo FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Chengdu Better City
    alias_name: Chengdu Rongcheng FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Qingdao Youth Island
    alias_name: Qingdao West Coast FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Henan Jianye
    alias_name: Henan
  - entity_type: team
    source_name: oddspapi
    canonical_name: Sichuan Jiuniu
    alias_name: Shenzhen Peng City
  - entity_type: team
    source_name: oddspapi
    canonical_name: Ulsan Hyundai FC
    alias_name: Ulsan HD FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Jeju United FC
    alias_name: Jeju SK FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Asan Mugunghwa
    alias_name: Chungnam Asan FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: AEK Athens FC
    alias_name: AEK Athens
  - entity_type: team
    source_name: oddspapi
    canonical_name: Olympiakos Piraeus
    alias_name: Olympiacos Piraeus
  - entity_type: team
    source_name: oddspapi
    canonical_name: Al-Ittihad FC
    alias_name: Al-Ittihad Club
  - entity_type: team
    source_name: oddspapi
    canonical_name: Al-Qadisiyah FC
    alias_name: Al Qadsiah
  - entity_type: team
    source_name: oddspapi
    canonical_name: Al-Hilal Saudi FC
    alias_name: Al Hilal SFC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Volos NFC
    alias_name: Volos NPS
  - entity_type: team
    source_name: oddspapi
    canonical_name: Al Taawon
    alias_name: Al-Taawoun FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Al-Ettifaq
    alias_name: Al-Ittifaq FC
  - entity_type: team
    source_name: oddspapi
    canonical_name: Panetolikos
    alias_name: Panaitolikos Agrinio
  - entity_type: team
    source_name: oddspapi
    canonical_name: Larisa
    alias_name: AE Larissa FC
