leagues:
  - name: Premier League
    country: England
    api_football_id: 39
    enabled: true
    priority: 100
  - name: La Liga
    country: Spain
    api_football_id: 140
    enabled: true
    priority: 98
  - name: Bundesliga
    country: Germany
    api_football_id: 78
    enabled: true
    priority: 97
  - name: Serie A
    country: Italy
    api_football_id: 135
    enabled: true
    priority: 96
  - name: Ligue 1
    country: France
    api_football_id: 61
    enabled: true
    priority: 95
  - name: UEFA Champions League
    country: World
    api_football_id: 2
    enabled: true
    priority: 94
  - name: UEFA Europa League
    country: World
    api_football_id: 3
    enabled: true
    priority: 93
  - name: UEFA Europa Conference League
    country: World
    api_football_id: 848
    enabled: true
    priority: 92
  - name: Championship
    country: England
    api_football_id: 40
    enabled: true
    priority: 88
  - name: 2. Bundesliga
    country: Germany
    api_football_id: 79
    enabled: true
    priority: 87
  - name: Segunda División
    country: Spain
    api_football_id: 141
    enabled: true
    priority: 86
  - name: Serie B
    country: Italy
    api_football_id: 136
    enabled: true
    priority: 85
  - name: Ligue 2
    country: France
    api_football_id: 62
    enabled: true
    priority: 84
  - name: Primeira Liga
    country: Portugal
    api_football_id: 94
    enabled: true
    priority: 83
  - name: Eredivisie
    country: Netherlands
    api_football_id: 88
    enabled: true
    priority: 82
  - name: Eerste Divisie
    country: Netherlands
    api_football_id: 89
    enabled: true
    priority: 81
  - name: Jupiler Pro League
    country: Belgium
    api_football_id: 144
    enabled: true
    priority: 80
  - name: Süper Lig
    country: Turkey
    api_football_id: 203
    enabled: true
    priority: 79
  - name: Premiership
    country: Scotland
    api_football_id: 179
    enabled: true
    priority: 78
  - name: Super League 1
    country: Greece
    api_football_id: 197
    enabled: true
    priority: 77
  - name: Bundesliga
    country: Austria
    api_football_id: 218
    enabled: true
    priority: 76
  - name: Super League
    country: Switzerland
    api_football_id: 207
    enabled: true
    priority: 75
  - name: Liga I
    country: Romania
    api_football_id: 283
    enabled: true
    priority: 74
  - name: Premier League
    country: Russia
    api_football_id: 235
    enabled: true
    priority: 73
  - name: Ekstraklasa
    country: Poland
    api_football_id: 106
    enabled: true
    priority: 72
  - name: Superliga
    country: Denmark
    api_football_id: 119
    enabled: true
    priority: 71
  - name: Liga Profesional Argentina
    country: Argentina
    api_football_id: 128
    enabled: true
    priority: 70
  - name: Serie A
    country: Brazil
    api_football_id: 71
    enabled: true
    priority: 69
  - name: Primera División
    country: Chile
    api_football_id: 265
    enabled: true
    priority: 68
  - name: Veikkausliiga
    country: Finland
    api_football_id: 244
    enabled: true
    priority: 67
  - name: Allsvenskan
    country: Sweden
    api_football_id: 113
    enabled: true
    priority: 66
  - name: Superettan
    country: Sweden
    api_football_id: 114
    enabled: true
    priority: 65
  - name: League One
    country: England
    api_football_id: 41
    enabled: true
    priority: 64
  - name: Eliteserien
    country: Norway
    api_football_id: 103
    enabled: true
    priority: 63
  - name: J1 League
    country: Japan
    api_football_id: 98
    enabled: true
    priority: 61
  - name: J2 League
    country: Japan
    api_football_id: 99
    enabled: false
    priority: 60
  - name: K League 1
    country: South-Korea
    api_football_id: 292
    enabled: true
    priority: 59
  - name: K League 2
    country: South-Korea
    api_football_id: 293
    enabled: true
    priority: 58
  - name: A-League
    country: Australia
    api_football_id: 188
    enabled: true
    priority: 57
  - name: Pro League
    country: Saudi-Arabia
    api_football_id: 307
    enabled: true
    priority: 56
  - name: Super League
    country: China
    api_football_id: 169
    enabled: true
    priority: 55
  - name: Major League Soccer
    country: USA
    api_football_id: 253
    enabled: true
    priority: 54
  - name: 1. Division
    country: Norway
    api_football_id: 104
    enabled: false
    priority: 53
  - name: Ykkösliiga
    country: Finland
    api_football_id: 1087
    enabled: false
    priority: 52
  - name: Premier Division
    country: Ireland
    api_football_id: 357
    enabled: false
    priority: 51
  - name: Liga 1
    country: Indonesia
    api_football_id: 274
    enabled: false
    priority: 50
  - name: 1. Division
    country: Denmark
    api_football_id: 120
    enabled: false
    priority: 49
